mot:

test_mot:

arbre:
	clang -c -Wall -Wextra -pedantic -O0 -g3 -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls arbre.c
	clang -c -Wall -Wextra -pedantic -O0 -g3 -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls test_arbre.c
	clang -Wall -Wextra -pedantic -O0 -g3 -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls test_arbre.o arbre.o -o test_arbre
	



pattern:

test_pattern:

main:

clean_mot:

clean_arbre:

clean_pattern:

clean_main: